name: RSS → Telegram (hourly)

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: rss-telegram-hourly
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python main.py

      - name: Upload logs as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: run-logs
          path: logs/*.log
          if-no-files-found: ignore
          retention-days: 14

      - name: Commit state & logs
        if: always()
        run: |
          git config user.email "actions@github.com"
          git config user.name "github-actions"
          # подтянем свежие коммиты, если параллельно были изменения
          git pull --rebase || true
          # добавляем state (он не в .gitignore)
          git add storage/news_state.json
          # форсим логи, они в .gitignore
          git add -f logs/*.log || true
          # коммитим, если есть изменения
          git commit -m "chore: update state & logs [skip ci]" || echo "Nothing to commit"
          git push || echo "Nothing to push"
